ait/views/chat.py
from flask import render_template, Blueprint
from flask_login import current_user, login_required
from ait import db_fire, socketio
from flask_socketio import send

chat =Blueprint('chat',__name__)

@socketio.on("message")
def sendMessage(message):
    message = current_user.username+ ": " + message
    print(message)
    send(message, broadcast=True)

@chat.route('/chat')
@login_required
def chat_app():
    username = current_user.username
    user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()

    return render_template('chat.html', username = username, user_data = user_data)
    

ait/views/connection.py
from flask import Blueprint, render_template, abort, url_for, redirect, request, flash
from flask_login import current_user, login_required
from ait import db_fire
from datetime import datetime
from ait.models import User

from datetime import date

connect =Blueprint('connection',__name__)

def roleProvider(username):
    try:
        passYear =username.split('_')[1][0:2]
        year =int('20' + passYear)
        currYear = int(date.today().year)

        if (year<currYear-4) :
            return 'Alumini'
        else :
            return 'Student'
    except:
        return None
    


@connect.route('/connection')
@login_required
def connection():
    doc_ref = db_fire.collection('connection').document(current_user.username)
    doc = doc_ref.get()
    type = db_fire.collection('connection').document(current_user.username).get().to_dict()
    print(type)
    user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()
    return render_template('connection.html', user_data = user_data, type = type)

@connect.route('/connection/send/<string:username>')
@login_required
def send_req(username):
    if username == current_user.username:
        abort(403)
    else:
        doc_ref =   db_fire.collection('connection').document(current_user.username)
        user_data = db_fire.collection('Alumini').document(username).get().to_dict()
        data = db_fire.collection('connection').document(current_user.username).get()
        
        if data.exists:
            print(data.to_dict())
            temp = data.to_dict()
            if user_data['username'] in data.to_dict().keys():
                print("hello in userdata")
                temp.pop(user_data['username'])
            
            else:    
                temp.update({ 
                    user_data['username'] :{
                    'username' : user_data['username'],
                    'profile_url' : user_data['profile_url'],
                    'created_at' : datetime.utcnow()
                    }
                    })
            db_fire.collection('connection').document(current_user.username).set( temp ,merge = True)
            
        else:
            temp = { 
                user_data['username'] :{
                'username' : user_data['username'],
                'profile_url' : user_data['profile_url'],
                'created_at' : datetime.utcnow()
                }
                }
            doc_ref.set(temp, merge = True)
                
        role = 'Alumini'
        return redirect(url_for('profile.user',username = username, role = role))

@connect.route('/connection/remove/<string:username>')
@login_required
def remove_req(username):
    if username == current_user.username:
        abort(403)
    else:
        data_user = db_fire.collection('connection').document(current_user.username).get().to_dict()
        print(data_user)
        print(type(data_user))
        del data_user[username]
        print(data_user)
        db_fire.collection('connection').document(current_user.username).set( data_user)
        role = 'Alumini'
        return redirect(url_for('profile.user',username = username, role = role))

@connect.route('/connection/<string:type>/<string:username>')
@login_required
def action_req(username,type):
    if username == current_user.username:
        abort(403)
    else:
        doc_ref =   db_fire.collection('connection').document(current_user.username)
        doc = doc_ref.get()

        if doc.exists:
            if type == "accept":
                data = doc.to_dict()['pending']
                data.remove(username)
                
                if 'accept' in doc.to_dict().keys():
                    accept_data = doc.to_dict()['accept']
                    accept_data.connectionend(username)
                else:
                    accept_data = [username]
                
                doc_ref.set({'accept': accept_data},merge = True)
                doc_ref.set({'pending': data},merge = True)

            if type == "reject":
                data = doc.to_dict()['pending']
                data.remove(username)
                doc_ref.set({'pending': data},merge = True)

        return redirect(url_for('home.home_latest'))
    
@connect.route('/search/<string:username>', methods=['GET','POST'])
@login_required
def search_user(username):
        role =roleProvider(username)
        if (role==None):
            flash('Invalid Username.','danger')
            return redirect(url_for('home.home_latest'))
        if username == current_user.username:
            return redirect (url_for('profile.account'))
        else:
            posts = db_fire.collection('post').where('username','==',username).get()
            user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()
            profile_data = db_fire.collection(role).document(username).get().to_dict()
            type = db_fire.collection('connection').document(current_user.username).get()
            
            value = False
            
            if type.exists:
                if username in type.to_dict().keys():
                    value = True 
            print(profile_data)
            return render_template('user.html', profile_data = profile_data,user_data = user_data, posts = posts, value = value  )

ait/views/home.py
from flask import Blueprint, render_template
from flask_login import current_user, login_required
from ait import db_fire
from firebase_admin import firestore

home =Blueprint('home',__name__)

@home.route('/')
@home.route('/home/latest')
@login_required
def home_latest():
    user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()
    posts = db_fire.collection('post').order_by("date_created", direction=firestore.Query.DESCENDING).get()
    return render_template('home.html', title = 'Home', user_data = user_data, posts = posts)

@home.route('/home/top')
@login_required
def home_top():
    user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()
    posts = db_fire.collection("post").order_by("likes", direction=firestore.Query.DESCENDING).get()
    return render_template('home_top.html', title = 'Home', user_data = user_data, posts = posts)

ait/views/post.py
from flask import Blueprint, render_template, abort, url_for, redirect, jsonify, request, flash
from flask_login import current_user, login_required
from firebase_admin import storage

from ait import db_fire
from ait.forms import PostForm

import os
import secrets
from io import BytesIO
from datetime import datetime

post =Blueprint('post',__name__)

@post.route('/get_post')
@login_required
def get_post():
    view_post = render_template('./post/view_post.html')
    data = {'remain': view_post}
    return jsonify(data)

def save_post_media(form_picture,username):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    blob = storage.bucket().blob('post/' +username + '/' + picture_fn)
    file_stream = BytesIO()
    form_picture.save(file_stream)
    blob.upload_from_string(
        file_stream.getvalue(),
        content_type=form_picture.content_type
    )
    blob.make_public()
    print(blob.public_url)

    return blob.public_url

@post.route('/post/new', methods= ['GET','POST'])
@login_required
def new_post():
    if current_user.role != "Alumini":
        abort(403)
    form = PostForm()
    user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()
    if form.validate_on_submit():
            
        data = { "username" : current_user.username,
        "title" : form.title.data,
        "content" : form.content.data,
        "media" : '',
        "likes" : [],
        "comments" : {},
        "date_created" : datetime.utcnow(),
        "profile_url" : user_data['profile_url'],
        "post_id" : current_user.username + datetime.utcnow().strftime(r'%Y%m%d%H%M%S'),
        "role" : current_user.role
        }
        if form.picture.data:
            picture_file = save_post_media(form.picture.data, current_user.username)
            data['media'] = picture_file

        id = current_user.username + data['date_created'].strftime(r'%Y%m%d%H%M%S')
        db_fire.collection('post').document(id).set(data)
        flash('Post Added.', 'success')
        return redirect(url_for('home.home_latest'))
    return render_template('new_post.html', title='New Post',form=form, legend='New Post', user_data = user_data)

@post.route('/comment/<string:post_id>', methods=['POST'])
@login_required
def add_comment(post_id):
    if request.method == "POST":
        username = current_user.username
        date_created = datetime.utcnow()
        comment = request.form.get("comment")
        id = username + date_created.strftime(r'%Y%m%d%H%M%S')
        user_data = db_fire.collection(current_user.role).document(current_user.username).get().to_dict()

        data = {
            id :{
            "date_created" : date_created,
            "comment" : comment,
            "username" : current_user.username,
            "profile_url" : user_data['profile_url']
            }
        }
        db_fire.collection('post').document(post_id).set({"comments": data}, merge = True)
        flash('Comment Added.', 'success')
        return redirect(url_for('home.home_latest'))

@post.route('/like/<string:post_id>', methods=['POST'])
@login_required
def like(post_id):
        if request.method == "POST":
            result = db_fire.collection('post').document(post_id).get().to_dict()
            if current_user.username in result['likes']:
                temp = db_fire.collection('post').document(post_id).get().to_dict()['likes']
                temp.remove(current_user.username)
                db_fire.collection('post').document(post_id).set({'likes': temp}, merge =True)

            else:
                result['likes'].append(current_user.username)
                db_fire.collection('post').document(post_id).set(result, merge = True)
        flash('Post Liked.', 'success')
        return redirect(url_for('home.home_latest'))

ait/templates/layout/auth_layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">


    {% if title %}
    <title>AIT - {{ title }}</title>
    {% else %}
    <title>AIT</title>
    {% endif %}

    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{{ url_for('static', filename='assets/img/favicon.png') }}" rel="icon">
    <link href="{{ url_for('static', filename='assets/img/favicon.png') }}assets/img/apple-touch-icon.png"
        rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{{ url_for('static', filename='assets/css/style.css') }}" rel="stylesheet">

</head>

<body>
    

    {% block content %}

    {% endblock content%}}

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>


    <!-- Template Main JS File -->
    <script src="{{ url_for('static', filename='assets/js/main.js') }}"></script>

</body>

</html>

ait/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">


    {% if title %}
    <title>AIT - {{ title }}</title>
    {% else %}
    <title>AIT</title>
    {% endif %}

    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{{ url_for('static', filename='assets/img/favicon.png') }}" rel="icon">
    <link href="{{ url_for('static', filename='assets/img/favicon.png') }}assets/img/apple-touch-icon.png"
        rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='assets/vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{{ url_for('static', filename='assets/css/style.css') }}" rel="stylesheet">

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/998b34ac07.js" crossorigin="anonymous"></script>

</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">

        <div class="d-flex align-items-center justify-content-between">
            <a href="{{ url_for('home.home_latest') }}" class="logo d-flex align-items-center">
                <img src="{{ url_for('static',filename='assets/img/logo.png' ) }}" alt="">
                <span class="d-none d-lg-block">AIT</span>
            </a>
            <i class="bi bi-list toggle-sidebar-btn"></i>
        </div><!-- End Logo -->

        <div class="search-bar">
            <form class="search-form d-flex align-items-center" method="POST" action="#">
                <input type="text" name="query" placeholder="Search Username" title="Enter search keyword">
                <button type="submit" title="Search"><i class="bi bi-search"></i></button>
            </form>
        </div><!-- End Search Bar -->

        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">

                <li class="nav-item d-block d-lg-none">
                    <a class="nav-link nav-icon search-bar-toggle " href="#">
                        <i class="bi bi-search"></i>
                    </a>
                </li><!-- End Search Icon-->

                <li class="nav-item dropdown pe-3">

                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">

                        {% with profile_url = user_data['profile_url'] %}
                        {% if profile_url == '' %}
                        <img class="rounded-circle me-2"
                            src="{{ url_for('static',filename='/profile_pic/default.jpeg' ) }}" width="40" height="40">
                        {% else %}
                        <img class="rounded-circle me-2" src="{{user_data['profile_url']}}" width="40" height="40">

                        {% endif %}
                        {% endwith %}

                        <span class="d-none d-md-block dropdown-toggle ps-2">{{user_data['name']}}</span>
                    </a><!-- End Profile Iamge Icon -->

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                        <li class="dropdown-header">
                            <h6>{{user_data['name']}}</h6>
                            <span>{{current_user.role}}</span>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="{{url_for('profile.account')}}">
                                <i class="bi bi-person"></i>
                                <span>My Profile</span>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="{{url_for('profile.account')}}">
                                <i class="bi bi-gear"></i>
                                <span>Account Settings</span>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <!-- <li>
                            <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
                                <i class="bi bi-question-circle"></i>
                                <span>Need Help?</span>
                            </a>
                        </li> -->
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center"
                                href="{{ url_for('authentication.logout') }}">
                                <i class="bi bi-box-arrow-right"></i>
                                <span>Sign Out</span>
                            </a>
                        </li>

                    </ul><!-- End Profile Dropdown Items -->
                </li><!-- End Profile Nav -->

            </ul>
        </nav><!-- End Icons Navigation -->

    </header>
    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">

            <li class="nav-item">
                <a class="nav-link " href="{{ url_for('home.home_latest' ) }}">
                    <i class="bi bi-grid"></i>
                    <span>Dashboard</span>
                </a>
            </li><!-- End Dashboard Nav -->

            {% if current_user.role=='Alumini' %}
            <li class="nav-item">
                <a class="nav-link " href="{{ url_for('post.new_post' ) }}">
                    <i class="bi bi-plus-square"></i>
                    <span>New Post</span>
                </a>
            </li><!-- End New Post Nav -->
            {% endif %}

            <li class="nav-item">
                <a class="nav-link " href="{{ url_for('connection.connection' ) }}">
                    <i class="fa-solid fa-user-plus"></i>
                    <span>Connection</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link " href="{{ url_for('chat.chat_app' ) }}">
                    <i class="fa-regular fa-comment me-2"></i>
                    <span>Global Chat</span>
                </a>
            </li>

            <li class="nav-item">


            <li class="nav-heading">Pages</li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="{{url_for('profile.account')}}">
                    <i class="bi bi-person"></i>
                    <span>Profile</span>
                </a>
            </li><!-- End Profile Page Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" href="https://github.com/sahilkamate03/AIT-Alumini">
                    <i class="fa-brands fa-github" style="color: #4154f1;"></i>
                    <span>Source Code</span>
                </a>
            </li><!-- End Profile Page Nav -->


            <!-- End Blank Page Nav -->

        </ul>

    </aside><!-- End Sidebar-->

    {% block content %}

    {% endblock content%}}

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
        <div class="copyright">
            &copy; Copyright <strong><span>AIT</span></strong>. All Rights Reserved
        </div>

    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="{{ url_for('static', filename='assets/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

    <!-- Template Main JS File -->
    <script src="{{ url_for('static', filename='assets/js/main.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/js/search.js') }}"></script>


</body>

</html>