ait/views/authentication.py
from dotenv import load_dotenv
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import current_user, login_user, logout_user
from firebase_admin import auth
import pyrebase

from ait import db_fire
from ait.models import User
from ait import db_fire, pyrebase
from ait.forms import LoginForm, RegistrationForm, PasswordRestForm, EmailVerificationForm

import os
from datetime import date
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

load_dotenv()
authentication =Blueprint('authentication',__name__)
pyrebase_auth = pyrebase.auth()

def roleProvider(email):
    year =int('20' + email.split('@')[0].split('_')[1][0:2])
    currYear = int(date.today().year)

    if (year<currYear-4) :
        return 'Alumini'
    else :
        return 'Student'


def send_verification_email(email):
    sender = os.getenv('EMAIL')
    verification_link =auth.generate_email_verification_link(email)
    recipient = email
    subject = 'Verify your email for AIT-Website'

    body = f'''
    Hello {email.split('@')[0]},

    Follow this link to verify your email address.

    {verification_link}

    If you didn’t ask to verify this address, you can ignore this email.

    Thanks
    '''

    message = MIMEMultipart()
    message['From'] = sender
    message['To'] = recipient
    message['Subject'] = subject
    message.attach(MIMEText(body, 'plain'))

    smtp_server = 'smtp.gmail.com'
    smtp_port = 587
    smtp_username = os.getenv('EMAIL')
    smtp_password = os.getenv('EMAIL_PWD')

    with smtplib.SMTP(smtp_server, smtp_port) as smtp:
        smtp.ehlo()
        smtp.starttls()
        smtp.ehlo()
        smtp.login(smtp_username, smtp_password)
        smtp.sendmail(sender, recipient, message.as_string())

def reset_password(email):
    sender = os.getenv('EMAIL')
    reset_link =auth.generate_password_reset_link(email)
    recipient = email
    subject = 'Reset your password for AIT-Website'

    body = f'''
    Hello {email.split('@')[0]},

    Follow this link to reset your email address.

    {reset_link}

    If you didn’t ask to reset this address, you can ignore this email.

    Thanks
    '''

    message = MIMEMultipart()
    message['From'] = sender
    message['To'] = recipient
    message['Subject'] = subject
    message.attach(MIMEText(body, 'plain'))

    smtp_server = 'smtp.gmail.com'
    smtp_port = 587
    smtp_username = os.getenv('EMAIL')
    smtp_password = os.getenv('EMAIL_PWD')

    with smtplib.SMTP(smtp_server, smtp_port) as smtp:
        smtp.ehlo()
        smtp.starttls()
        smtp.ehlo()
        smtp.login(smtp_username, smtp_password)
        smtp.sendmail(sender, recipient, message.as_string())


@authentication.route('/login', methods= ['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('home.home_latest'))
    form = LoginForm()
    if form.validate_on_submit():
        email =form.email.data
        password =form.password.data
        try:
            user_id =auth.get_user_by_email(email)
        except:
            flash('User not found. Create Account.', 'info')
            return redirect(url_for('authentication.register'))
        
        print(user_id.email_verified)
        if (email == 'admin_18185@aitpune.edu.in'):
            pass
        elif not(user_id.email_verified):
            flash('Verify your email.', 'info')
            return render_template('./auth_page/pages-login.html', title = 'Login', form=form)
            
        try:
            info= pyrebase_auth.sign_in_with_email_and_password(email, password)
            user_id =info['localId']
            user = User(user_id,email)
            next_page = request.args.get('next')
            login_user(user, remember=form.remember.data)
            return redirect(next_page) if next_page else redirect(url_for('home.home_latest'))
        except Exception as e: 
            flash('Login Unsuccessful. Please check email and password', 'danger')
            print(e)
            return redirect(url_for('authentication.login'))
        
    return render_template('./auth_page/pages-login.html', title = 'Login', form=form)

@authentication.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('authentication.login'))

@authentication.route('/register',methods = ['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('home.home_latest'))
    form = RegistrationForm()
    if form.validate_on_submit():
        print('success')
        email =form.email.data
        password =form.password.data
        role =roleProvider(email)
        data= {"name": form.name.data, 
        "username": email.split("@")[0],
        "email" : email,
        "role" : role,
        "add" : "-",
        "phone" : "-",
        "about" : "Write about yourself.",
        "profile_url" : "",
        "verified" : False
        }
        try:
            db_fire.collection(role).document(form.email.data.split("@")[0]).set(data)
            auth.create_user(email =email, password =password)
            send_verification_email(email)
            flash(f'Verification link send to email.','info')
            return redirect(url_for('authentication.login'))
        except Exception as e:
            print(e)
        
    return render_template('./auth_page/pages-register.html', title = 'Register', form =form)

@authentication.route('/password_reset', methods= ['GET', 'POST'])
def password_reset():
    form = PasswordRestForm()
    if form.validate_on_submit():
        email =form.email.data
        try:
            auth.get_user_by_email(email)
        except:
            return redirect(url_for('authentication.register'))
        
        try:
            reset_password(email)
            return redirect(url_for('authentication.login'))
        except Exception as e: 
            flash('Login Unsuccessful. Please check email and password', 'danger')
            print(e)
            return redirect(url_for('authentication.login'))
        
    return render_template('./auth_page/pwd_reset.html', title = 'Password Reset', form=form)

@authentication.route('/send_verification_email', methods= ['GET', 'POST'])
def verify_email():
    form = EmailVerificationForm()
    if form.validate_on_submit():
        email =form.email.data
        try:
            auth.get_user_by_email(email)
        except:
            flash('User not found. Create Account.', 'info')
            return redirect(url_for('authentication.register'))
        
        try:
            print(email)
            send_verification_email(email)
            flash('Verification email send.', 'info')
            return redirect(url_for('authentication.login'))
        except Exception as e: 
            flash('Unable to send. Please check later.', 'danger')
            print(e)
            return redirect(url_for('authentication.login'))
        
    return render_template('./auth_page/verify_email.html', title = 'Verify Account', form=form)

ait/templates/auth_page/pages-login.html
{% extends "./layout/auth_layout.html" %}
{% block content %}
<main>
  <div class="container">

    <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">
            <div class="d-flex justify-content-center py-4">
              <a href="index.html" class="logo d-flex align-items-center w-auto">
                <img src="{{ url_for('static',filename='assets/img/logo.png' ) }}" alt="">
                <span class="d-none d-lg-block">AIT</span>
              </a>
            </div><!-- End Logo -->

            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{category}}  mx-auto " role="alert">
              {{message}}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
            <div class="card mb-3">

              <div class="card-body">

                <div class="pt-4 pb-2">
                  <h5 class="card-title text-center pb-0 fs-4">Login to Your Account</h5>
                  <p class="text-center small">Enter your Email & Password to login</p>
                </div>

                <form class="row g-3 needs-validation" method="POST" action="">
                  {{ form.hidden_tag() }}
                  <fieldset class="form-group">
                    <div class="col-12">
                      <div class="form-group">
                        {{ form.email.label(class="form-label") }}
                        {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                          {% for error in form.email.errors %}
                          <span>{{ error }}</span>
                          {% endfor %}
                        </div>
                        {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                      </div>

                    </div>

                    <div class="col-12">
                      <div class="form-group">
                        {{ form.password.label(class="form-label") }}
                        {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                          {% for error in form.password.errors %}
                          <span>{{ error }}</span>
                          {% endfor %}
                        </div>
                        {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                        {% endif %}
                      </div>
                    </div>

                    <div class="col-12">
                      <div class="form-check">
                        {{ form.remember(class="form-check-input") }}
                        {{ form.remember.label(class="form-check-label") }}
                      </div>
                    </div>

                    <div class="col-12">
                      <div class="btn btn-primary w-100 mt-2">
                        {{ form.submit(class="btn btn-primary w-100") }}
                      </div>
                    </div>

                    <div class="col-12">
                      <p class="small mb-0">Don't have account? <a
                          href="{{ url_for('authentication.register') }}">Create an
                          account</a></p>
                    </div>
                  </fieldset>

                  <small class="text-muted ml-2">
                    <a href="{{ url_for('authentication.password_reset') }}">Forgot Password?</a>
                  </small>

                  <small class="text-muted ml-2">
                    <a href="{{ url_for('authentication.verify_email') }}">Send Verification Email?</a>
                  </small>
                </form>

              </div>
            </div>



          </div>
        </div>
      </div>

    </section>

  </div>
</main><!-- End #main -->
{% endblock content%}}

ait/templates/auth_page/pages-register.html
{% extends "./layout/auth_layout.html" %}
{% block content %}
<main>
  <div class="container">

    <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

            <div class="d-flex justify-content-center py-4">
              <a href="index.html" class="logo d-flex align-items-center w-auto">
                <img src="{{ url_for('static',filename='assets/img/logo.png' )}}" alt="">
                <span class="d-none d-lg-block">AIT</span>
              </a>
            </div><!-- End Logo -->

            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{category}}  mx-auto " role="alert">
              {{message}}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}

            <div class="card mb-3">

              <div class="card-body">

                <div class="pt-4 pb-2">
                  <h5 class="card-title text-center pb-0 fs-4">Create an Account</h5>
                  <p class="text-center small">Enter your personal details to create account</p>
                </div>

                <form method="POST" action="" class="row g-3 needs-validation">
                  {{ form.hidden_tag() }}
                  <fieldset class="form-group">
                    <div class="col-12">
                      <div class="form-group">
                        {{ form.name.label(class="form-label") }}

                        {% if form.name.errors %}
                        {{ form.name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                          {% for error in form.name.errors %}
                          <span>{{ error }}</span>
                          {% endfor %}
                        </div>
                        {% else %}
                        {{ form.name(class="form-control form-control-lg") }}
                        {% endif %}
                      </div>
                    </div>

                    <div class="col-12">
                      <div class="form-group">
                        {{ form.email.label(class="form-label") }}
                        {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                          {% for error in form.email.errors %}
                          <span>{{ error }}</span>
                          {% endfor %}
                        </div>
                        {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                      </div>
                    </div>

                    <div class="col-12">
                      <div class="form-group">
                        {{ form.password.label(class="form-label") }}
                        {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                          {% for error in form.password.errors %}
                          <span>{{ error }}</span>
                          {% endfor %}
                        </div>
                        {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                        {% endif %}
                      </div>
                    </div>

                    <div class="col-12">
                      <div class="form-group">
                        {{ form.confirm_password.label(class="form-control-label") }}
                        {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                          {% for error in form.confirm_password.errors %}
                          <span>{{ error }}</span>
                          {% endfor %}
                        </div>
                        {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                        {% endif %}
                      </div>
                    </div>

                    <div class="col-12 mt-3">
                      <div class="form-check">
                        <input class="form-check-input" name="terms" type="checkbox" value="" id="acceptTerms" required>
                        <label class="form-check-label" for="acceptTerms">I agree and accept the <a href="#">terms and
                            conditions</a></label>
                        <div class="invalid-feedback">You must agree before submitting.</div>
                      </div>
                    </div>
                    <div class="col-12 mt-2">
                      {{ form.submit(class="btn btn-primary w-100") }}
                    </div>
                    <div class="col-12 mt-2">
                      <p class="small mb-0">Already have an account? <a href="{{ url_for('authentication.login') }}">Log
                          in</a></p>
                    </div>
                  </fieldset>
                </form>

              </div>
            </div>


          </div>
        </div>
      </div>

    </section>

  </div>
</main><!-- End #main -->
{% endblock content%}}

ait/templates/auth_page/pwd_reset.html
{% extends "./layout/auth_layout.html" %}
{% block content %}
<main>
  <div class="container">

    <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

            <div class="d-flex justify-content-center py-4">
              <a href="index.html" class="logo d-flex align-items-center w-auto">
                <img src="{{ url_for('static',filename='assets/img/logo.png' ) }}" alt="">
                <span class="d-none d-lg-block">AIT</span>
              </a>
            </div><!-- End Logo -->

            <div class="card mb-3">

              <div class="card-body">

                <div class="pt-4 pb-2">
                  <h5 class="card-title text-center pb-0 fs-4">Password Reset</h5>
                  <p class="text-center small">Enter your Email</p>
                </div>

                <form class="row g-3 needs-validation" method="POST" action="">
                  {{ form.hidden_tag() }}
                  <fieldset class="form-group">
                    <div class="col-12">
                      <div class="form-group">
                        {{ form.email.label(class="form-label") }}
                        {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                          {% for error in form.email.errors %}
                          <span>{{ error }}</span>
                          {% endfor %}
                        </div>
                        {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                      </div>

                    </div>

                    <div class="col-12">
                      <div class="btn btn-primary w-100 mt-2">
                        {{ form.submit(class="btn btn-primary w-100") }}
                      </div>
                    </div>

                  </fieldset>

                </form>

              </div>
            </div>



          </div>
        </div>
      </div>

    </section>

  </div>
</main><!-- End #main -->
{% endblock content%}}

ait/templates/auth_page/verify_email.html
{% extends "./layout/auth_layout.html" %}
{% block content %}
<main>
  <div class="container">

    <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

            <div class="d-flex justify-content-center py-4">
              <a href="index.html" class="logo d-flex align-items-center w-auto">
                <img src="{{ url_for('static',filename='assets/img/logo.png' ) }}" alt="">
                <span class="d-none d-lg-block">AIT</span>
              </a>
            </div><!-- End Logo -->

            <div class="card mb-3">

              <div class="card-body">

                <div class="pt-4 pb-2">
                  <h5 class="card-title text-center pb-0 fs-4">Send Verification Email</h5>
                  <p class="text-center small">Enter your Email</p>
                </div>

                <form class="row g-3 needs-validation" method="POST" action="">
                  {{ form.hidden_tag() }}
                  <fieldset class="form-group">
                    <div class="col-12">
                      <div class="form-group">
                        {{ form.email.label(class="form-label") }}
                        {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                          {% for error in form.email.errors %}
                          <span>{{ error }}</span>
                          {% endfor %}
                        </div>
                        {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                      </div>

                    </div>

                    <div class="col-12">
                      <div class="btn btn-primary w-100 mt-2">
                        {{ form.submit(class="btn btn-primary w-100") }}
                      </div>
                    </div>

                  </fieldset>

                </form>

              </div>
            </div>



          </div>
        </div>
      </div>

    </section>

  </div>
</main><!-- End #main -->
{% endblock content%}}